version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      swc-node:
        patterns:
          - "@swc-node/*"
      tsconfig:
        patterns:
          - "@tsconfig/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
